targets:
  $default:
    builders:
      bunker_lib:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*
            - test/integration/**/*

builders:
  bunker:
    target: ":bunker_lib"
    import: "package:bunker_lib/bunker_lib.dart"
    build_extensions: { ".dart": [ ".bunker.dart" ] }
    builder_factories: [ "bunkerBuilder" ]
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
    runs_before: [ "json_serializable|json_serializable" ]
